// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const supabaseUrl = "https://qzxksxzibjrqmeuqzsex.supabase.co";
const supabaseKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF6eGtzeHppYmpycW1ldXF6c2V4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MjY2MTk1MTUsImV4cCI6MjA0MjE5NTUxNX0.q17i1bMWF0jOVXd6VVxDSo2Xakl52YgiA8XqKLkJbRM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabaseKey);